id = "clice"
name = "clice"
version = "0.1.0"
schema_version = 1
authors = ["AXiX-official <axix@mail.ustc.edu.cn>"]
description = "C++ support"
repository = "https://github.com/AXiX-official/clice-zed"

[language_servers.clice]
name = "clice"
language = "C++"
