id = "clice"
name = "clice"
version = "0.1.0"
schema_version = 1
authors = ["clice-project"]
description = "C++ support"
repository = "https://github.com/clice-project/clice-zed"

[language_servers.clice]
name = "clice"
language = "C++"
